---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
      - name: trades
        image: ghcr.io/tacoman99/trades:0.1.5-beta.1746468463
        imagePullPolicy: Always
        #
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: "trades"
        #
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
      imagePullSecrets:
        - name: ghcr-secret
