---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trades-historical
  namespace: historical
  labels:
    app: trades-historical
spec:
  schedule: "5 * * * *"  # Run every 5 minutes
  concurrencyPolicy: Forbid  # Don't start new job if previous one is still running
  successfulJobsHistoryLimit: 3  # Keep history of last 3 successful jobs
  failedJobsHistoryLimit: 1  # Keep history of last failed job
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          labels:
            app: trades-historical
        spec:
          restartPolicy: OnFailure
          containers:
          - name: trades-historical
            image: trades:dev
            imagePullPolicy: Never # Use the local image
            env:
            - name: KAFKA_BROKER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: backfill-technical-indicators
                  key: KAFKA_BROKER_ADDRESS
            - name: KAFKA_TOPIC_NAME
              valueFrom:
                configMapKeyRef:
                  name: backfill-technical-indicators
                  key: TRADES_TOPIC
            - name: LIVE_OR_HISTORICAL
              value: "historical"
            - name: LAST_N_DAYS
              valueFrom:
                configMapKeyRef:
                  name: backfill-technical-indicators
                  key: LAST_N_DAYS
            resources:
              limits:
                cpu: 1000m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 512Mi