#
# https://kubernetes.io/docs/concepts/workloads/controllers/job/
#
---
apiVersion: batch/v1
kind: Job
metadata:
  name: technical-indicators-historical
  namespace: rwml
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: technical-indicators
        image: technical-indicators:dev
        imagePullPolicy: Never # Use the local image
        env:
        #
        - name: KAFKA_BROKER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backfill-config
              key: KAFKA_BROKER_ADDRESS
        #
        - name: KAFKA_INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-config
              key: CANDLES_TOPIC
        #
        - name: KAFKA_OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: backfill-config
              key: TECHNICAL_INDICATORS_TOPIC
        #
        - name: KAFKA_CONSUMER_GROUP
          value: "technical_indicators_group"
        #
        - name: CANDLE_SECONDS
          valueFrom:
            configMapKeyRef:
              name: backfill-config
              key: CANDLE_SECONDS